[[main]]
    name = "Team"
    url = "/#team"
    weight = 1

[[main]]
    name = "Docs"
    url = "/#docs"
    weight = 2

[[main]]
    name = "Docs"
    url = "/#docs"
    weight = 3

[[main]]
    name = "News"
    url = "/#news"
    weight = 4

[[social]]
    name = 'Twitter'
    url = 'https://twitter.com'
    weight = '1'
    [social.params]
        icon = ''